const rolesData = [
  { value: "Developer", label: "Developer", isSelected: false },
  { value: "Designer", label: "Designer", isSelected: false },
  { value: "Manager", label: "Manager", isSelected: false },
  { value: "Engineer", label: "Engineer", isSelected: false },
  { value: "Architect", label: "Architect", isSelected: false },
  { value: "Analyst", label: "Analyst", isSelected: false },
  { value: "Administrator", label: "Administrator", isSelected: false },
  { value: "Programmer", label: "Programmer", isSelected: false },
  { value: "Consultant", label: "Consultant", isSelected: false },
  { value: "Specialist", label: "Specialist", isSelected: false },
  { value: "Coordinator", label: "Coordinator", isSelected: false },
  { value: "Supervisor", label: "Supervisor", isSelected: false },
  { value: "Technician", label: "Technician", isSelected: false },

  { value: "Advisor", label: "Advisor", isSelected: false },
  { value: "Director", label: "Director", isSelected: false },
  { value: "Assistant", label: "Assistant", isSelected: false },
  { value: "Auditor", label: "Auditor", isSelected: false },
  { value: "Planner", label: "Planner", isSelected: false },
  { value: "Researcher", label: "Researcher", isSelected: false },
  { value: "Technologist", label: "Technologist", isSelected: false },
];

const experienceData = [
  { value: "1", label: "1 year", isSelected: false },
  { value: "2", label: "2 years", isSelected: false },
  { value: "3", label: "3 years", isSelected: false },
  { value: "4", label: "4 years", isSelected: false },
  { value: "5", label: "5 years", isSelected: false },
  { value: "6", label: "6 years", isSelected: false },
  { value: "7", label: "7 years", isSelected: false },
  { value: "8", label: "8 years", isSelected: false },
  { value: "9", label: "9 years", isSelected: false },
  { value: "10", label: "10 years", isSelected: false },
  { value: "10+", label: "10+ years", isSelected: false },
];

const employeesData = [
  { value: "1-10", label: "1-10", isSelected: false },
  { value: "11-20", label: "11-20", isSelected: false },
  { value: "21-40", label: "21-40", isSelected: false },
  { value: "41-50", label: "41-50", isSelected: false },
  { value: "51-100", label: "51-100", isSelected: false },
  { value: "101+", label: "101+", isSelected: false },
];

const baseSalaryData = [
  { value: "0", label: "0 L", isSelected: false },
  { value: "10", label: "10 L", isSelected: false },
  { value: "20", label: "20 L", isSelected: false },
  { value: "30", label: "30 L", isSelected: false },
  { value: "40", label: "40 L", isSelected: false },
  { value: "50", label: "50 L", isSelected: false },
  { value: "60", label: "60 L", isSelected: false },
  { value: "70", label: "70 L", isSelected: false },
  { value: "70+", label: "70+ L", isSelected: false },
];

const remoteOptionsData = [
  { value: "Remote", label: "Remote", isSelected: false },
  { value: "Hybrid", label: "Hybrid", isSelected: false },
  { value: "In-Office", label: "In-Office", isSelected: false },
];

const techStackData = [
  { value: "JavaScript", label: "JavaScript", isSelected: false },
  { value: "Python", label: "Python", isSelected: false },
  { value: "Java", label: "Java", isSelected: false },
  { value: "C++", label: "C++", isSelected: false },
  { value: "Ruby", label: "Ruby", isSelected: false },
  { value: "C#", label: "C#", isSelected: false },
  { value: "PHP", label: "PHP", isSelected: false },
  { value: "Swift", label: "Swift", isSelected: false },
  { value: "Kotlin", label: "Kotlin", isSelected: false },
  { value: "TypeScript", label: "TypeScript", isSelected: false },
  { value: "Go", label: "Go", isSelected: false },
  { value: "Rust", label: "Rust", isSelected: false },
  { value: "Scala", label: "Scala", isSelected: false },
  { value: "Ruby on Rails", label: "Ruby on Rails", isSelected: false },
  { value: "Node.js", label: "Node.js", isSelected: false },
  { value: "React", label: "React", isSelected: false },
  { value: "Angular", label: "Angular", isSelected: false },
  { value: "Vue.js", label: "Vue.js", isSelected: false },
  { value: "Express.js", label: "Express.js", isSelected: false },
  { value: "Django", label: "Django", isSelected: false },
  { value: "Flask", label: "Flask", isSelected: false },
  { value: "Spring Boot", label: "Spring Boot", isSelected: false },
  { value: "Laravel", label: "Laravel", isSelected: false },
  { value: "ASP.NET", label: "ASP.NET", isSelected: false },
  { value: "Ruby on Rails", label: "Ruby on Rails", isSelected: false },
  { value: "iOS", label: "iOS", isSelected: false },
  { value: "Android", label: "Android", isSelected: false },
  { value: "Unity", label: "Unity", isSelected: false },
  { value: "TensorFlow", label: "TensorFlow", isSelected: false },
  { value: "PyTorch", label: "PyTorch", isSelected: false },
  { value: "Keras", label: "Keras", isSelected: false },
  { value: "Scikit-learn", label: "Scikit-learn", isSelected: false },
  { value: "MongoDB", label: "MongoDB", isSelected: false },
  { value: "MySQL", label: "MySQL", isSelected: false },
  { value: "PostgreSQL", label: "PostgreSQL", isSelected: false },
  { value: "SQLite", label: "SQLite", isSelected: false },
  { value: "Firebase", label: "Firebase", isSelected: false },
  { value: "AWS", label: "AWS", isSelected: false },
  { value: "Azure", label: "Azure", isSelected: false },
  { value: "Google Cloud", label: "Google Cloud", isSelected: false },
  { value: "Docker", label: "Docker", isSelected: false },
  { value: "Kubernetes", label: "Kubernetes", isSelected: false },
];

export {
  rolesData,
  experienceData,
  employeesData,
  baseSalaryData,
  remoteOptionsData,
  techStackData,
};
